spring:
  application:
    name: 'bvpay'
  datasource:
    url: jdbc:postgresql://localhost:5432/bvpaydb
    username: myuser
    password: mypass
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect